### ISSUE TITLE
Config File Separation

### ISSUE THREAD

**Issue by MChambers1992** [Nelderson/MV_Online#10]
Currently in the main config.js file we have several sections used across numerous files, moving forward separating these into smaller config files could be beneficial as it would follow the separation of concerns principle. Having these smaller more granular files means that we can access only the properties we need in modules rather than having unnecessary ones.

The end result for this change would be a file structure similar to the example below;
- chatConfig.js
- serverConfig.js
- loggingConfig.js
- databaseConfig.js
- loginConfig.js

**Comment by Nelderson** [comment]
I want to do this for all api and socket module configs going forward.  The only reason I haven't gone back and changed all the core configs is because all my video and written documentation is for that main config file.  It makes it easier to take all the 100% necessary configs and place them in one file for now.

This is something I will consider on the next major update.

**Comment by MChambers1992** [comment]
Totally fair reasoning with regards to the video tutorials it makes it very easy for people to set up currently. 

Related issue that arises from this would be a public project roadmap, is there a document with plans and features that are wanting to be done in later versions available? It would make development of new features or refactoring a bit easier for outside developers like myself who are keen to contribute.
