### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by KevinAT** [Nelderson/MV_Online#32]
is support for the Steamworks API planned? obviously i can't imagine this to work if you'd just throw together MV_Online and say OrangeGreenworks and expect them to not break each other, or at least everything would have to be made seperate, once for steam and once for the self hosted server... so do you think it'd be possible to add steam support later on and let users chose which to use? (user login, cloud, achievements, screenshots, friends, etc, etc)

**Comment by Nelderson** [comment]
I would recommend Hudell's plugin for Steam integration. found here:
https://forums.rpgmakerweb.com/index.php?threads/orangegreenworks-steam-integration-with-achievements-and-time-log.59469/

If you wanted to make a login system based off steam credentials it's totally possible.  I just won't be doing it since you can deploy this in so many other ways.  Too specific for this project.
