### ISSUE TITLE
MV_Online with ABS

### ISSUE THREAD

**Issue by towwi** [Nelderson/MV_Online#45]
Hey! Im using Quasis abs plugin. Me and my friend can see each other in game but we both have our own mobs. I mean like, My friend attacks monster and kills it but to me all i can see him walking around even tho he really is killing a monster. Havent set up the cloudsave yet. Do you need it so we could both kill the monster same time and see my when my friend attacks it. I cant see his attack animations either.
Any ideas?

**Comment by tentran2k1** [comment]
Good idea !

**Comment by DatTranPro** [comment]
nice

**Comment by Nelderson** [comment]
I've explained in my overview that this is by default a passive system.  That's not to say it can't work with ABS, but it requires a lot of integration with that plugin specifically.  Not to mention a way of making all ai decisions on the server.  

Long story short, I'm not going to be implementing this anytime soon.  I'll reconsider if you get Quasi to help me out, since he made the plugin and would know the system way better then me.
