### ISSUE TITLE
Bug's when Player Transfer on a Map and Login!

### ISSUE THREAD

**Issue by Soubi92** [Nelderson/MV_Online#64]
Found a Bug when Players transfer to a Map, other "Netplayers" not see when  standing still on the Map.
When Player Logout from Game and Re-Login, the Name over the Head the Players disappears, when Transer to a next Map, the names are there again.

**Comment by Nelderson** [comment]
1. Players standing still and not rendering on the map is how I intended it.  I might change it in the future, but my reasoning for doing it initially was if the netplayer doesn't move, then it's not necessary for your computer resources to render it. 

2. I'm assuming you mean game end scene?  Because there is no official logout process.  This isn't a bug so much as how rpgmaker works with coming back into the same map when coming out of the game end scene.  And the reason it reappears after a  map transfer is the game_player object is refreshed automatically.
